#!/bin/bash -e

SECRET=~/.config/easy2fa/secret
COUNTER=~/.config/easy2fa/counter
mkdir -p ~/.config/easy2fa

input_to_file() {
    # if the given file does not exist, create it from user
    # input, with the given prompt and optional default
    local filename=$1
    local prompt=$2
    local default=${3:-""}
    if [ ! -f "$filename" ]; then
        local input=""
        touch $filename
        chmod 600 $filename
        echo -n "$prompt"
        read input
        if test -z "$input"; then
            input=$default
        fi
        echo $input > $filename
    fi
}

which oathtool >/dev/null || { echo 'Please install oathtool'; exit 1; }

input_to_file $SECRET 'No 2FA found, enter new secret: '
chmod 400 $SECRET
input_to_file $COUNTER 'Start at counter (default=0): ' 0

OTP=$(oathtool -c $(cat $COUNTER) -b $(cat $SECRET))
echo $(($(cat $COUNTER) + 1)) > $COUNTER

echo $OTP
notify-send "2FA OTP copied to clipboard: $(echo $OTP | xclip -f -selection clipboard || echo 'Not possible, please install xclip')"
