name: easy2fa
version: master
summary: Easy to use two-factor-auth client for cli
description: |
  A simple wrapper around oathtool for two-factor-auth. Please run
  it once from the commandline to set up.
grade: devel
confinement: strict

apps:
  easy2fa:
    command: easy2fa
    plugs: [ unity7 ]

parts:
  easy2fa:
    plugin: python
    source: https://github.com/lutostag/easy2fa.git
    stage-packages:
      - oathtool
      - xclip
      - libnotify-bin
      - python3-yaml
