name: otp
version: master
summary: A simple wrapper around oathtool for two-factor-auth
description: |
  A simple wrapper around oathtool for two-factor-auth. Please run
  it once from the commandline to set up.
grade: devel
confinement: strict

apps:
  otp:
    command: otp
    plugs: [ unity7 ]

parts:
  otp:
    source: git://github.com/lutostag/otp
    plugin: dump
    stage-packages:
      - oathtool
      - xclip
      - libnotify-bin
