name: easy2fa
version: master
icon: snap/gui/easy2fa.svg
summary: Easy to use two-factor-auth client for cli
description: |
  A simple wrapper around oathtool for two-factor-auth. Please run
  it once from the commandline to set up.
grade: stable
confinement: strict

apps:
  easy2fa:
    command: easy2fa
    plugs: [ unity7 ] # for clipboard permissions
  gui:
    command: desktop-launch $SNAP/bin/easy2fa.gui
    plugs: [ unity7 ]

parts:
  xcb-util-xrm:
    plugin: autotools
    source: https://github.com/Airblader/xcb-util-xrm.git
    prepare: |
      ./autogen.sh
    build-packages:
        - libxcb-util0-dev
        - libxcb1-dev
        - libx11-xcb-dev
        - xutils-dev
        - xvfb
  rofi:
    plugin: autotools
    source: https://github.com/DaveDavenport/rofi.git
    after: [desktop-gtk2, xcb-util-xrm]
    prepare: |
      autoreconf -i
    build-packages:
      - bison
      - flex
      - libpango1.0-dev
      - libstartup-notification0-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libxcb1-dev
      - libxcb-xkb-dev
      - libxcb-xinerama0-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-randr0-dev
      - libxcb-util0-dev
    stage-packages:
      - libc6
      - libcairo2
      - libglib2.0-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libstartup-notification0
      - libxcb-ewmh2
      - libxcb-icccm4
      - libxcb-util1
      - libxcb-xinerama0
      - libxcb-xkb1
      - libxcb1
      - libxkbcommon-x11-0
      - libxkbcommon0
  easy2fa:
    plugin: python
    source: https://github.com/lutostag/easy2fa.git
    after: [desktop-gtk2, rofi]
    stage-packages:
      - oathtool
      - xclip
      - libnotify-bin
      - python3-yaml
